### ISSUE TITLE
[BUG-UMC]Maybe crash when use UmcSession::GetMrcpSessionId()

### ISSUE THREAD

**Issue by VincentZhangHui** [unispeech/unimrcp#234]
if the end of MrcpSessionId is not '\0', it will crash or other unknown error.
---
![image](https://user-images.githubusercontent.com/33553029/54506285-c7e2aa00-4976-11e9-88ce-0e2e06fe9789.png)
![image](https://user-images.githubusercontent.com/33553029/54506355-00828380-4977-11e9-9585-e4203af2199b.png)

**Comment by michaelplevy** [comment]
Agreed. I never ran into a crash due to this, but the comment [in the docs](https://www.unimrcp.org/dox/html/structapt__str__t.html) has always given me concern.

**Comment by achaloyan** [comment]
Well, I agree that this is not a good practice in general.

However, while apt_str_t does not guarantee the underlying buffer to be always NULL terminated, the function apt_unique_id_generate() used to generate an MRCP session identified always sets the terminating '\0'.

So, this is more an academic discussion, especially taking into account that GetMrcpSessionId() is an internal function in sample client application not exposed in any public API.

Thanks for the note, though. And please feel free to reopen the issue, if I am missing anything here.

**Comment by VincentZhangHui** [comment]
Yes, I agree that. But sometimes my program crashed when I use std::string object += the MRCP session id. The stack is strlen("MRCPSESSIONID"). It is ok when I get length. So the function apt_unique_id_generate() used to generate an MRCP session identified may not always set the terminating '\0'. So maybe you can pay attention to it. @achaloyan

**Comment by achaloyan** [comment]
Actually, apt_unique_id_generate() is irrelevant in this case, as this function is used on the server side.

Quickly looking through the client-side code, I see that the buffer is created in apt_id_resource_generate(), which is also NULL terminated.

Sorry, I have absolutely no time to dig further. If you are able to identify the exact flaw causing the problem, I can take a closer look. Otherwise, you may implement an alternate version of GetMrcpSessionId() returning the length of the id too, which would be the right thing to do, anyway. Bu t again, umc is a sample client application, which can/should serve as a prototype.

**Comment by VincentZhangHui** [comment]
Okay, thank you very much.
