### ISSUE TITLE
unimrcp crash when timer reschedule

### ISSUE THREAD

**Issue by MaxYinXB** [unispeech/unimrcp#310]
unimrcp version: 1.2.0
FreeSWITCH version: 1.8.5

Using unimrcp for mrcp interaction within FreeSWITCH, but it crashed on timer reschedule, here is the bt
![图片](https://user-images.githubusercontent.com/40413562/171312719-ae7c2e40-6773-4b84-92c5-d9f34ae3d0df.png)

line of 228 is:

![图片](https://user-images.githubusercontent.com/40413562/171312915-6f5cbb0e-6b4e-4d7b-9ae1-2166663755c6.png)

it looks like the memory address was corrupted.  

by the way, we did not modify any code of unimrcp except `apt_timers_reschedule` which we showed.

any useful advice will be appreciated!

**Comment by achaloyan** [comment]
Please note that the latest version of UniMRCP is 1.7.0. I do not recall what was in 1.2.0.

Also, it is not very clear which component actually crashed in this scenario. Is it the client stack running within FS or UniMRCP server. If the latter, then the memory corruption might be caused by the use of a 3-rd party plugin which is loaded into the common address space.
